### ISSUE TITLE
Dependency alert for "Visual Studio MPF 15.0" in VS 2019

### ISSUE THREAD

**Issue by DNF-SaS** [GregTrevellick/SolutionOpenPopUp#3]
Just tried to install the SolutionOpenPopUp-Extension into VS2019 RC:

![image](https://user-images.githubusercontent.com/3329952/54679257-2343a200-4b07-11e9-8c60-4b323bfa9b48.png)

**Comment by GregTrevellick** [comment]
Thanks for raising this issue - I have just fixed this in version 1.0.45 which is now live in the marketplace. 

Please try again, thanks.

**Comment by DNF-SaS** [comment]
@GregTrevellick The Dependency Alert went away, great! :-)
Unfortunately, in VS 2019 RC.4 no Popup is shown.
SolutionPopUp.txt is placed in the same directory where the .sln-File is.

**Comment by GregTrevellick** [comment]
Hi - can you confirm the version of the extension that you are using and that it is enabled, and also the file name is SolutionOpenPopUp.txt (SolutionPopUp.txt)- thanks

**Comment by DNF-SaS** [comment]
@GregTrevellick For testing, I have created both files right beside the .sln-File:

![image](https://user-images.githubusercontent.com/3329952/55107382-74d4c980-50d1-11e9-84b0-f688e9d38a0c.png)

**Comment by DNF-SaS** [comment]
Naming the file "SolutionOpenPopUp.txt" works!
Only SolutionPopUp.txt does not.
